export type Country = {
    dial: string;
    name: string;
    emoji: string;
    iso2: string;
    unicode: string;
};

export const countryCodes: Country[] = [
    {
        dial: "995",
        name: "Georgia",
        emoji: "🇬🇪",
        iso2: "GE",
        unicode: "\u{1F1EC}\u{1F1EA}",
    },
    {
        dial: "44",
        name: "United Kingdom",
        emoji: "🇬🇧",
        iso2: "GB",
        unicode: "\u{1F1EC}\u{1F1E7}",
    },
    {
        dial: "1",
        name: "United States",
        emoji: "🇺🇸",
        iso2: "US",
        unicode: "\u{1F1FA}\u{1F1F8}",
    },
    {
        dial: "380",
        name: "Ukraine",
        emoji: "🇺🇦",
        iso2: "UA",
        unicode: "\u{1F1FA}\u{1F1E6}",
    },
    {
        dial: "90",
        name: "Turkey",
        emoji: "🇹🇷",
        iso2: "TR",
        unicode: "\u{1F1F9}\u{1F1F7}",
    },
    {
        dial: "81",
        name: "Japan",
        emoji: "🇯🇵",
        iso2: "JP",
        unicode: "\u{1F1EF}\u{1F1F5}",
    },
    {
        dial: "30",
        name: "Greece",
        emoji: "🇬🇷",
        iso2: "GR",
        unicode: "\u{1F1EC}\u{1F1F7}",
    },
    {
        dial: "55",
        name: "Brazil",
        emoji: "🇧🇷",
        iso2: "BR",
        unicode: "\u{1F1E7}\u{1F1F7}",
    },
    {
        dial: "93",
        name: "Afghanistan",
        emoji: "🇦🇫",
        iso2: "AF",
        unicode: "\u{1F1E6}\u{1F1EB}",
    },
    {
        dial: "355",
        name: "Albania",
        emoji: "🇦🇱",
        iso2: "AL",
        unicode: "\u{1F1E6}\u{1F1F1}",
    },
    {
        dial: "213",
        name: "Algeria",
        emoji: "🇩🇿",
        iso2: "DZ",
        unicode: "\u{1F1E9}\u{1F1FF}",
    },
    {
        dial: "1684",
        name: "American Samoa",
        emoji: "🇦🇸",
        iso2: "AS",
        unicode: "\u{1F1E6}\u{1F1F8}",
    },
    {
        dial: "376",
        name: "Andorra",
        emoji: "🇦🇩",
        iso2: "AD",
        unicode: "\u{1F1E6}\u{1F1E9}",
    },
    {
        dial: "244",
        name: "Angola",
        emoji: "🇦🇴",
        iso2: "AO",
        unicode: "\u{1F1E6}\u{1F1F4}",
    },
    {
        dial: "1264",
        name: "Anguilla",
        emoji: "🇦🇮",
        iso2: "AI",
        unicode: "\u{1F1E6}\u{1F1EE}",
    },
    {
        dial: "1268",
        name: "Antigua and Barbuda",
        emoji: "🇦🇬",
        iso2: "AG",
        unicode: "\u{1F1E6}\u{1F1EC}",
    },
    {
        dial: "54",
        name: "Argentina",
        emoji: "🇦🇷",
        iso2: "AR",
        unicode: "\u{1F1E6}\u{1F1F7}",
    },
    {
        dial: "374",
        name: "Armenia",
        emoji: "🇦🇲",
        iso2: "AM",
        unicode: "\u{1F1E6}\u{1F1F2}",
    },
    {
        dial: "297",
        name: "Aruba",
        emoji: "🇦🇼",
        iso2: "AW",
        unicode: "\u{1F1E6}\u{1F1FC}",
    },
    {
        dial: "61",
        name: "Australia",
        emoji: "🇦🇺",
        iso2: "AU",
        unicode: "\u{1F1E6}\u{1F1FA}",
    },
    {
        dial: "43",
        name: "Austria",
        emoji: "🇦🇹",
        iso2: "AT",
        unicode: "\u{1F1E6}\u{1F1F9}",
    },
    {
        dial: "994",
        name: "Azerbaijan",
        emoji: "🇦🇿",
        iso2: "AZ",
        unicode: "\u{1F1E6}\u{1F1FF}",
    },
    {
        dial: "1242",
        name: "Bahamas",
        emoji: "🇧🇸",
        iso2: "BS",
        unicode: "\u{1F1E7}\u{1F1F8}",
    },
    {
        dial: "973",
        name: "Bahrain",
        emoji: "🇧🇭",
        iso2: "BH",
        unicode: "\u{1F1E7}\u{1F1ED}",
    },
    {
        dial: "880",
        name: "Bangladesh",
        emoji: "🇧🇩",
        iso2: "BD",
        unicode: "\u{1F1E7}\u{1F1E9}",
    },
    {
        dial: "1246",
        name: "Barbados",
        emoji: "🇧🇧",
        iso2: "BB",
        unicode: "\u{1F1E7}\u{1F1E7}",
    },
    {
        dial: "375",
        name: "Belarus",
        emoji: "🇧🇾",
        iso2: "BY",
        unicode: "\u{1F1E7}\u{1F1FE}",
    },
    {
        dial: "32",
        name: "Belgium",
        emoji: "🇧🇪",
        iso2: "BE",
        unicode: "\u{1F1E7}\u{1F1EA}",
    },
    {
        dial: "501",
        name: "Belize",
        emoji: "🇧🇿",
        iso2: "BZ",
        unicode: "\u{1F1E7}\u{1F1FF}",
    },
    {
        dial: "229",
        name: "Benin",
        emoji: "🇧🇯",
        iso2: "BJ",
        unicode: "\u{1F1E7}\u{1F1EF}",
    },
    {
        dial: "1441",
        name: "Bermuda",
        emoji: "🇧🇲",
        iso2: "BM",
        unicode: "\u{1F1E7}\u{1F1F2}",
    },
    {
        dial: "975",
        name: "Bhutan",
        emoji: "🇧🇹",
        iso2: "BT",
        unicode: "\u{1F1E7}\u{1F1F9}",
    },
    {
        dial: "591",
        name: "Bolivia",
        emoji: "🇧🇴",
        iso2: "BO",
        unicode: "\u{1F1E7}\u{1F1F4}",
    },
    {
        dial: "387",
        name: "Bosnia and Herzegovina",
        emoji: "🇧🇦",
        iso2: "BA",
        unicode: "\u{1F1E7}\u{1F1E6}",
    },
    {
        dial: "267",
        name: "Botswana",
        emoji: "🇧🇼",
        iso2: "BW",
        unicode: "\u{1F1E7}\u{1F1FC}",
    },
    {
        dial: "246",
        name: "British Indian Ocean Territory",
        emoji: "🇮🇴",
        iso2: "IO",
        unicode: "\u{1F1EE}\u{1F1F4}",
    },
    {
        dial: "1284",
        name: "British Virgin Islands",
        emoji: "🇻🇬",
        iso2: "VG",
        unicode: "\u{1F1FB}\u{1F1EC}",
    },
    {
        dial: "673",
        name: "Brunei",
        emoji: "🇧🇳",
        iso2: "BN",
        unicode: "\u{1F1E7}\u{1F1F3}",
    },
    {
        dial: "359",
        name: "Bulgaria",
        emoji: "🇧🇬",
        iso2: "BG",
        unicode: "\u{1F1E7}\u{1F1EC}",
    },
    {
        dial: "226",
        name: "Burkina Faso",
        emoji: "🇧🇫",
        iso2: "BF",
        unicode: "\u{1F1E7}\u{1F1EB}",
    },
    {
        dial: "257",
        name: "Burundi",
        emoji: "🇧🇮",
        iso2: "BI",
        unicode: "\u{1F1E7}\u{1F1EE}",
    },
    {
        dial: "855",
        name: "Cambodia",
        emoji: "🇰🇭",
        iso2: "KH",
        unicode: "\u{1F1F0}\u{1F1ED}",
    },
    {
        dial: "237",
        name: "Cameroon",
        emoji: "🇨🇲",
        iso2: "CM",
        unicode: "\u{1F1E8}\u{1F1F2}",
    },
    {
        dial: "1",
        name: "Canada",
        emoji: "🇨🇦",
        iso2: "CA",
        unicode: "\u{1F1E8}\u{1F1E6}",
    },
    {
        dial: "238",
        name: "Cape Verde",
        emoji: "🇨🇻",
        iso2: "CV",
        unicode: "\u{1F1E8}\u{1F1FB}",
    },
    {
        dial: "599",
        name: "Caribbean Netherlands",
        emoji: "🇧🇶",
        iso2: "BQ",
        unicode: "\u{1F1E7}\u{1F1F6}",
    },
    {
        dial: "1345",
        name: "Cayman Islands",
        emoji: "🇰🇾",
        iso2: "KY",
        unicode: "\u{1F1F0}\u{1F1FE}",
    },
    {
        dial: "236",
        name: "Central African Republic",
        emoji: "🇨🇫",
        iso2: "CF",
        unicode: "\u{1F1E8}\u{1F1EB}",
    },
    {
        dial: "235",
        name: "Chad",
        emoji: "🇹🇩",
        iso2: "TD",
        unicode: "\u{1F1F9}\u{1F1E9}",
    },
    {
        dial: "56",
        name: "Chile",
        emoji: "🇨🇱",
        iso2: "CL",
        unicode: "\u{1F1E8}\u{1F1F1}",
    },
    {
        dial: "86",
        name: "China",
        emoji: "🇨🇳",
        iso2: "CN",
        unicode: "\u{1F1E8}\u{1F1F3}",
    },
    {
        dial: "61",
        name: "Christmas Island",
        emoji: "🇨🇽",
        iso2: "CX",
        unicode: "\u{1F1E8}\u{1F1FD}",
    },
    {
        dial: "61",
        name: "Cocos (Keeling) Islands",
        emoji: "🇨🇨",
        iso2: "CC",
        unicode: "\u{1F1E8}\u{1F1E8}",
    },
    {
        dial: "57",
        name: "Colombia",
        emoji: "🇨🇴",
        iso2: "CO",
        unicode: "\u{1F1E8}\u{1F1F4}",
    },
    {
        dial: "269",
        name: "Comoros",
        emoji: "🇰🇲",
        iso2: "KM",
        unicode: "\u{1F1F0}\u{1F1F2}",
    },
    {
        dial: "243",
        name: "Congo",
        emoji: "🇨🇩",
        iso2: "CD",
        unicode: "\u{1F1E8}\u{1F1E9}",
    },
    {
        dial: "242",
        name: "Congo",
        emoji: "🇨🇬",
        iso2: "CG",
        unicode: "\u{1F1E8}\u{1F1EC}",
    },
    {
        dial: "682",
        name: "Cook Islands",
        emoji: "🇨🇰",
        iso2: "CK",
        unicode: "\u{1F1E8}\u{1F1F0}",
    },
    {
        dial: "506",
        name: "Costa Rica",
        emoji: "🇨🇷",
        iso2: "CR",
        unicode: "\u{1F1E8}\u{1F1F7}",
    },
    {
        dial: "225",
        name: "Côte d’Ivoire",
        emoji: "🇨🇮",
        iso2: "CI",
        unicode: "\u{1F1E8}\u{1F1EE}",
    },
    {
        dial: "385",
        name: "Croatia",
        emoji: "🇭🇷",
        iso2: "HR",
        unicode: "\u{1F1ED}\u{1F1F7}",
    },
    {
        dial: "53",
        name: "Cuba",
        emoji: "🇨🇺",
        iso2: "CU",
        unicode: "\u{1F1E8}\u{1F1FA}",
    },
    {
        dial: "599",
        name: "Curaçao",
        emoji: "🇨🇼",
        iso2: "CW",
        unicode: "\u{1F1E8}\u{1F1FC}",
    },
    {
        dial: "357",
        name: "Cyprus",
        emoji: "🇨🇾",
        iso2: "CY",
        unicode: "\u{1F1E8}\u{1F1FE}",
    },
    {
        dial: "420",
        name: "Czech Republic",
        emoji: "🇨🇿",
        iso2: "CZ",
        unicode: "\u{1F1E8}\u{1F1FF}",
    },
    {
        dial: "45",
        name: "Denmark",
        emoji: "🇩🇰",
        iso2: "DK",
        unicode: "\u{1F1E9}\u{1F1F0}",
    },
    {
        dial: "253",
        name: "Djibouti",
        emoji: "🇩🇯",
        iso2: "DJ",
        unicode: "\u{1F1E9}\u{1F1EF}",
    },
    {
        dial: "1767",
        name: "Dominica",
        emoji: "🇩🇲",
        iso2: "DM",
        unicode: "\u{1F1E9}\u{1F1F2}",
    },
    {
        dial: "1",
        name: "Dominican Republic",
        emoji: "🇩🇴",
        iso2: "DO",
        unicode: "\u{1F1E9}\u{1F1F4}",
    },
    {
        dial: "593",
        name: "Ecuador",
        emoji: "🇪🇨",
        iso2: "EC",
        unicode: "\u{1F1EA}\u{1F1E8}",
    },
    {
        dial: "20",
        name: "Egypt",
        emoji: "🇪🇬",
        iso2: "EG",
        unicode: "\u{1F1EA}\u{1F1EC}",
    },
    {
        dial: "503",
        name: "El Salvador",
        emoji: "🇸🇻",
        iso2: "SV",
        unicode: "\u{1F1F8}\u{1F1FB}",
    },
    {
        dial: "240",
        name: "Equatorial Guinea",
        emoji: "🇬🇶",
        iso2: "GQ",
        unicode: "\u{1F1EC}\u{1F1F6}",
    },
    {
        dial: "291",
        name: "Eritrea",
        emoji: "🇪🇷",
        iso2: "ER",
        unicode: "\u{1F1EA}\u{1F1F7}",
    },
    {
        dial: "372",
        name: "Estonia",
        emoji: "🇪🇪",
        iso2: "EE",
        unicode: "\u{1F1EA}\u{1F1EA}",
    },
    {
        dial: "251",
        name: "Ethiopia",
        emoji: "🇪🇹",
        iso2: "ET",
        unicode: "\u{1F1EA}\u{1F1F9}",
    },
    {
        dial: "500",
        name: "Falkland Islands",
        emoji: "🇫🇰",
        iso2: "FK",
        unicode: "\u{1F1EB}\u{1F1F0}",
    },
    {
        dial: "298",
        name: "Faroe Islands",
        emoji: "🇫🇴",
        iso2: "FO",
        unicode: "\u{1F1EB}\u{1F1F4}",
    },
    {
        dial: "679",
        name: "Fiji",
        emoji: "🇫🇯",
        iso2: "FJ",
        unicode: "\u{1F1EB}\u{1F1EF}",
    },
    {
        dial: "358",
        name: "Finland",
        emoji: "🇫🇮",
        iso2: "FI",
        unicode: "\u{1F1EB}\u{1F1EE}",
    },
    {
        dial: "33",
        name: "France",
        emoji: "🇫🇷",
        iso2: "FR",
        unicode: "\u{1F1EB}\u{1F1F7}",
    },
    {
        dial: "594",
        name: "French Guiana",
        emoji: "🇬🇫",
        iso2: "GF",
        unicode: "\u{1F1EC}\u{1F1EB}",
    },
    {
        dial: "689",
        name: "French Polynesia",
        emoji: "🇵🇫",
        iso2: "PF",
        unicode: "\u{1F1F5}\u{1F1EB}",
    },
    {
        dial: "241",
        name: "Gabon",
        emoji: "🇬🇦",
        iso2: "GA",
        unicode: "\u{1F1EC}\u{1F1E6}",
    },
    {
        dial: "220",
        name: "Gambia",
        emoji: "🇬🇲",
        iso2: "GM",
        unicode: "\u{1F1EC}\u{1F1F2}",
    },
    {
        dial: "49",
        name: "Germany",
        emoji: "🇩🇪",
        iso2: "DE",
        unicode: "\u{1F1E9}\u{1F1EA}",
    },
    {
        dial: "233",
        name: "Ghana",
        emoji: "🇬🇭",
        iso2: "GH",
        unicode: "\u{1F1EC}\u{1F1ED}",
    },
    {
        dial: "350",
        name: "Gibraltar",
        emoji: "🇬🇮",
        iso2: "GI",
        unicode: "\u{1F1EC}\u{1F1EE}",
    },
    {
        dial: "299",
        name: "Greenland",
        emoji: "🇬🇱",
        iso2: "GL",
        unicode: "\u{1F1EC}\u{1F1F1}",
    },
    {
        dial: "1473",
        name: "Grenada",
        emoji: "🇬🇩",
        iso2: "GD",
        unicode: "\u{1F1EC}\u{1F1E9}",
    },
    {
        dial: "590",
        name: "Guadeloupe",
        emoji: "🇬🇵",
        iso2: "GP",
        unicode: "\u{1F1EC}\u{1F1F5}",
    },
    {
        dial: "1671",
        name: "Guam",
        emoji: "🇬🇺",
        iso2: "GU",
        unicode: "\u{1F1EC}\u{1F1FA}",
    },
    {
        dial: "502",
        name: "Guatemala",
        emoji: "🇬🇹",
        iso2: "GT",
        unicode: "\u{1F1EC}\u{1F1F9}",
    },
    {
        dial: "44",
        name: "Guernsey",
        emoji: "🇬🇬",
        iso2: "GG",
        unicode: "\u{1F1EC}\u{1F1EC}",
    },
    {
        dial: "224",
        name: "Guinea",
        emoji: "🇬🇳",
        iso2: "GN",
        unicode: "\u{1F1EC}\u{1F1F3}",
    },
    {
        dial: "245",
        name: "Guinea-Bissau",
        emoji: "🇬🇼",
        iso2: "GW",
        unicode: "\u{1F1EC}\u{1F1FC}",
    },
    {
        dial: "592",
        name: "Guyana",
        emoji: "🇬🇾",
        iso2: "GY",
        unicode: "\u{1F1EC}\u{1F1FE}",
    },
    {
        dial: "509",
        name: "Haiti",
        emoji: "🇭🇹",
        iso2: "HT",
        unicode: "\u{1F1ED}\u{1F1F9}",
    },
    {
        dial: "504",
        name: "Honduras",
        emoji: "🇭🇳",
        iso2: "HN",
        unicode: "\u{1F1ED}\u{1F1F3}",
    },
    {
        dial: "852",
        name: "Hong Kong",
        emoji: "🇭🇰",
        iso2: "HK",
        unicode: "\u{1F1ED}\u{1F1F0}",
    },
    {
        dial: "36",
        name: "Hungary",
        emoji: "🇭🇺",
        iso2: "HU",
        unicode: "\u{1F1ED}\u{1F1FA}",
    },
    {
        dial: "354",
        name: "Iceland",
        emoji: "🇮🇸",
        iso2: "IS",
        unicode: "\u{1F1EE}\u{1F1F8}",
    },
    {
        dial: "91",
        name: "India",
        emoji: "🇮🇳",
        iso2: "IN",
        unicode: "\u{1F1EE}\u{1F1F3}",
    },
    {
        dial: "62",
        name: "Indonesia",
        emoji: "🇮🇩",
        iso2: "ID",
        unicode: "\u{1F1EE}\u{1F1E9}",
    },
    {
        dial: "98",
        name: "Iran",
        emoji: "🇮🇷",
        iso2: "IR",
        unicode: "\u{1F1EE}\u{1F1F7}",
    },
    {
        dial: "964",
        name: "Iraq",
        emoji: "🇮🇶",
        iso2: "IQ",
        unicode: "\u{1F1EE}\u{1F1F6}",
    },
    {
        dial: "353",
        name: "Ireland",
        emoji: "🇮🇪",
        iso2: "IE",
        unicode: "\u{1F1EE}\u{1F1EA}",
    },
    {
        dial: "44",
        name: "Isle of Man",
        emoji: "🇮🇲",
        iso2: "IM",
        unicode: "\u{1F1EE}\u{1F1F2}",
    },
    {
        dial: "972",
        name: "Israel",
        emoji: "🇮🇱",
        iso2: "IL",
        unicode: "\u{1F1EE}\u{1F1F1}",
    },
    {
        dial: "39",
        name: "Italy",
        emoji: "🇮🇹",
        iso2: "IT",
        unicode: "\u{1F1EE}\u{1F1F9}",
    },
    {
        dial: "1876",
        name: "Jamaica",
        emoji: "🇯🇲",
        iso2: "JM",
        unicode: "\u{1F1EF}\u{1F1F2}",
    },
    {
        dial: "44",
        name: "Jersey",
        emoji: "🇯🇪",
        iso2: "JE",
        unicode: "\u{1F1EF}\u{1F1EA}",
    },
    {
        dial: "962",
        name: "Jordan",
        emoji: "🇯🇴",
        iso2: "JO",
        unicode: "\u{1F1EF}\u{1F1F4}",
    },
    {
        dial: "7",
        name: "Kazakhstan",
        emoji: "🇰🇿",
        iso2: "KZ",
        unicode: "\u{1F1F0}\u{1F1FF}",
    },
    {
        dial: "254",
        name: "Kenya",
        emoji: "🇰🇪",
        iso2: "KE",
        unicode: "\u{1F1F0}\u{1F1EA}",
    },
    {
        dial: "686",
        name: "Kiribati",
        emoji: "🇰🇮",
        iso2: "KI",
        unicode: "\u{1F1F0}\u{1F1EE}",
    },
    {
        dial: "383",
        name: "Kosovo",
        emoji: "🇽🇰",
        iso2: "XK",
        unicode: "\u{1F1FD}\u{1F1F0}",
    },
    {
        dial: "965",
        name: "Kuwait",
        emoji: "🇰🇼",
        iso2: "KW",
        unicode: "\u{1F1F0}\u{1F1FC}",
    },
    {
        dial: "996",
        name: "Kyrgyzstan",
        emoji: "🇰🇬",
        iso2: "KG",
        unicode: "\u{1F1F0}\u{1F1EC}",
    },
    {
        dial: "856",
        name: "Laos",
        emoji: "🇱🇦",
        iso2: "LA",
        unicode: "\u{1F1F1}\u{1F1E6}",
    },
    {
        dial: "371",
        name: "Latvia",
        emoji: "🇱🇻",
        iso2: "LV",
        unicode: "\u{1F1F1}\u{1F1FB}",
    },
    {
        dial: "961",
        name: "Lebanon",
        emoji: "🇱🇧",
        iso2: "LB",
        unicode: "\u{1F1F1}\u{1F1E7}",
    },
    {
        dial: "266",
        name: "Lesotho",
        emoji: "🇱🇸",
        iso2: "LS",
        unicode: "\u{1F1F1}\u{1F1F8}",
    },
    {
        dial: "231",
        name: "Liberia",
        emoji: "🇱🇷",
        iso2: "LR",
        unicode: "\u{1F1F1}\u{1F1F7}",
    },
    {
        dial: "218",
        name: "Libya",
        emoji: "🇱🇾",
        iso2: "LY",
        unicode: "\u{1F1F1}\u{1F1FE}",
    },
    {
        dial: "423",
        name: "Liechtenstein",
        emoji: "🇱🇮",
        iso2: "LI",
        unicode: "\u{1F1F1}\u{1F1EE}",
    },
    {
        dial: "370",
        name: "Lithuania",
        emoji: "🇱🇹",
        iso2: "LT",
        unicode: "\u{1F1F1}\u{1F1F9}",
    },
    {
        dial: "352",
        name: "Luxembourg",
        emoji: "🇱🇺",
        iso2: "LU",
        unicode: "\u{1F1F1}\u{1F1FA}",
    },
    {
        dial: "853",
        name: "Macau",
        emoji: "🇲🇴",
        iso2: "MO",
        unicode: "\u{1F1F2}\u{1F1F4}",
    },
    {
        dial: "389",
        name: "Macedonia",
        emoji: "🇲🇰",
        iso2: "MK",
        unicode: "\u{1F1F2}\u{1F1F0}",
    },
    {
        dial: "261",
        name: "Madagascar",
        emoji: "🇲🇬",
        iso2: "MG",
        unicode: "\u{1F1F2}\u{1F1EC}",
    },
    {
        dial: "265",
        name: "Malawi",
        emoji: "🇲🇼",
        iso2: "MW",
        unicode: "\u{1F1F2}\u{1F1FC}",
    },
    {
        dial: "60",
        name: "Malaysia",
        emoji: "🇲🇾",
        iso2: "MY",
        unicode: "\u{1F1F2}\u{1F1FE}",
    },
    {
        dial: "960",
        name: "Maldives",
        emoji: "🇲🇻",
        iso2: "MV",
        unicode: "\u{1F1F2}\u{1F1FB}",
    },
    {
        dial: "223",
        name: "Mali",
        emoji: "🇲🇱",
        iso2: "ML",
        unicode: "\u{1F1F2}\u{1F1F1}",
    },
    {
        dial: "356",
        name: "Malta",
        emoji: "🇲🇹",
        iso2: "MT",
        unicode: "\u{1F1F2}\u{1F1F9}",
    },
    {
        dial: "692",
        name: "Marshall Islands",
        emoji: "🇲🇭",
        iso2: "MH",
        unicode: "\u{1F1F2}\u{1F1ED}",
    },
    {
        dial: "596",
        name: "Martinique",
        emoji: "🇲🇶",
        iso2: "MQ",
        unicode: "\u{1F1F2}\u{1F1F6}",
    },
    {
        dial: "222",
        name: "Mauritania",
        emoji: "🇲🇷",
        iso2: "MR",
        unicode: "\u{1F1F2}\u{1F1F7}",
    },
    {
        dial: "230",
        name: "Mauritius",
        emoji: "🇲🇺",
        iso2: "MU",
        unicode: "\u{1F1F2}\u{1F1FA}",
    },
    {
        dial: "262",
        name: "Mayotte",
        emoji: "🇾🇹",
        iso2: "YT",
        unicode: "\u{1F1FE}\u{1F1F9}",
    },
    {
        dial: "52",
        name: "Mexico",
        emoji: "🇲🇽",
        iso2: "MX",
        unicode: "\u{1F1F2}\u{1F1FD}",
    },
    {
        dial: "691",
        name: "Micronesia",
        emoji: "🇫🇲",
        iso2: "FM",
        unicode: "\u{1F1EB}\u{1F1F2}",
    },
    {
        dial: "373",
        name: "Moldova",
        emoji: "🇲🇩",
        iso2: "MD",
        unicode: "\u{1F1F2}\u{1F1E9}",
    },
    {
        dial: "377",
        name: "Monaco",
        emoji: "🇲🇨",
        iso2: "MC",
        unicode: "\u{1F1F2}\u{1F1E8}",
    },
    {
        dial: "976",
        name: "Mongolia",
        emoji: "🇲🇳",
        iso2: "MN",
        unicode: "\u{1F1F2}\u{1F1F3}",
    },
    {
        dial: "382",
        name: "Montenegro",
        emoji: "🇲🇪",
        iso2: "ME",
        unicode: "\u{1F1F2}\u{1F1EA}",
    },
    {
        dial: "1664",
        name: "Montserrat",
        emoji: "🇲🇸",
        iso2: "MS",
        unicode: "\u{1F1F2}\u{1F1F8}",
    },
    {
        dial: "212",
        name: "Morocco",
        emoji: "🇲🇦",
        iso2: "MA",
        unicode: "\u{1F1F2}\u{1F1E6}",
    },
    {
        dial: "258",
        name: "Mozambique",
        emoji: "🇲🇿",
        iso2: "MZ",
        unicode: "\u{1F1F2}\u{1F1FF}",
    },
    {
        dial: "95",
        name: "Myanmar",
        emoji: "🇲🇲",
        iso2: "MM",
        unicode: "\u{1F1F2}\u{1F1F2}",
    },
    {
        dial: "264",
        name: "Namibia",
        emoji: "🇳🇦",
        iso2: "NA",
        unicode: "\u{1F1F3}\u{1F1E6}",
    },
    {
        dial: "674",
        name: "Nauru",
        emoji: "🇳🇷",
        iso2: "NR",
        unicode: "\u{1F1F3}\u{1F1F7}",
    },
    {
        dial: "977",
        name: "Nepal",
        emoji: "🇳🇵",
        iso2: "NP",
        unicode: "\u{1F1F3}\u{1F1F5}",
    },
    {
        dial: "31",
        name: "Netherlands",
        emoji: "🇳🇱",
        iso2: "NL",
        unicode: "\u{1F1F3}\u{1F1F1}",
    },
    {
        dial: "687",
        name: "New Caledonia",
        emoji: "🇳🇨",
        iso2: "NC",
        unicode: "\u{1F1F3}\u{1F1E8}",
    },
    {
        dial: "64",
        name: "New Zealand",
        emoji: "🇳🇿",
        iso2: "NZ",
        unicode: "\u{1F1F3}\u{1F1FF}",
    },
    {
        dial: "505",
        name: "Nicaragua",
        emoji: "🇳🇮",
        iso2: "NI",
        unicode: "\u{1F1F3}\u{1F1EE}",
    },
    {
        dial: "227",
        name: "Niger",
        emoji: "🇳🇪",
        iso2: "NE",
        unicode: "\u{1F1F3}\u{1F1EA}",
    },
    {
        dial: "234",
        name: "Nigeria",
        emoji: "🇳🇬",
        iso2: "NG",
        unicode: "\u{1F1F3}\u{1F1EC}",
    },
    {
        dial: "683",
        name: "Niue",
        emoji: "🇳🇺",
        iso2: "NU",
        unicode: "\u{1F1F3}\u{1F1FA}",
    },
    {
        dial: "672",
        name: "Norfolk Island",
        emoji: "🇳🇫",
        iso2: "NF",
        unicode: "\u{1F1F3}\u{1F1EB}",
    },
    {
        dial: "850",
        name: "North Korea",
        emoji: "🇰🇵",
        iso2: "KP",
        unicode: "\u{1F1F0}\u{1F1F5}",
    },
    {
        dial: "1670",
        name: "Northern Mariana Islands",
        emoji: "🇲🇵",
        iso2: "MP",
        unicode: "\u{1F1F2}\u{1F1F5}",
    },
    {
        dial: "47",
        name: "Norway",
        emoji: "🇳🇴",
        iso2: "NO",
        unicode: "\u{1F1F3}\u{1F1F4}",
    },
    {
        dial: "968",
        name: "Oman",
        emoji: "🇴🇲",
        iso2: "OM",
        unicode: "\u{1F1F4}\u{1F1F2}",
    },
    {
        dial: "92",
        name: "Pakistan",
        emoji: "🇵🇰",
        iso2: "PK",
        unicode: "\u{1F1F5}\u{1F1F0}",
    },
    {
        dial: "680",
        name: "Palau",
        emoji: "🇵🇼",
        iso2: "PW",
        unicode: "\u{1F1F5}\u{1F1FC}",
    },
    {
        dial: "970",
        name: "Palestine",
        emoji: "🇵🇸",
        iso2: "PS",
        unicode: "\u{1F1F5}\u{1F1F8}",
    },
    {
        dial: "507",
        name: "Panama",
        emoji: "🇵🇦",
        iso2: "PA",
        unicode: "\u{1F1F5}\u{1F1E6}",
    },
    {
        dial: "675",
        name: "Papua New Guinea",
        emoji: "🇵🇬",
        iso2: "PG",
        unicode: "\u{1F1F5}\u{1F1EC}",
    },
    {
        dial: "595",
        name: "Paraguay",
        emoji: "🇵🇾",
        iso2: "PY",
        unicode: "\u{1F1F5}\u{1F1FE}",
    },
    {
        dial: "51",
        name: "Peru",
        emoji: "🇵🇪",
        iso2: "PE",
        unicode: "\u{1F1F5}\u{1F1EA}",
    },
    {
        dial: "63",
        name: "Philippines",
        emoji: "🇵🇭",
        iso2: "PH",
        unicode: "\u{1F1F5}\u{1F1ED}",
    },
    {
        dial: "48",
        name: "Poland",
        emoji: "🇵🇱",
        iso2: "PL",
        unicode: "\u{1F1F5}\u{1F1F1}",
    },
    {
        dial: "351",
        name: "Portugal",
        emoji: "🇵🇹",
        iso2: "PT",
        unicode: "\u{1F1F5}\u{1F1F9}",
    },
    {
        dial: "1",
        name: "Puerto Rico",
        emoji: "🇵🇷",
        iso2: "PR",
        unicode: "\u{1F1F5}\u{1F1F7}",
    },
    {
        dial: "974",
        name: "Qatar",
        emoji: "🇶🇦",
        iso2: "QA",
        unicode: "\u{1F1F6}\u{1F1E6}",
    },
    {
        dial: "262",
        name: "Réunion",
        emoji: "🇷🇪",
        iso2: "RE",
        unicode: "\u{1F1F7}\u{1F1EA}",
    },
    {
        dial: "40",
        name: "Romania",
        emoji: "🇷🇴",
        iso2: "RO",
        unicode: "\u{1F1F7}\u{1F1F4}",
    },
    {
        dial: "250",
        name: "Rwanda",
        emoji: "🇷🇼",
        iso2: "RW",
        unicode: "\u{1F1F7}\u{1F1FC}",
    },
    {
        dial: "590",
        name: "Saint Barthélemy",
        emoji: "🇧🇱",
        iso2: "BL",
        unicode: "\u{1F1E7}\u{1F1F1}",
    },
    {
        dial: "290",
        name: "Saint Helena",
        emoji: "🇸🇭",
        iso2: "SH",
        unicode: "\u{1F1F8}\u{1F1ED}",
    },
    {
        dial: "1869",
        name: "Saint Kitts and Nevis",
        emoji: "🇰🇳",
        iso2: "KN",
        unicode: "\u{1F1F0}\u{1F1F3}",
    },
    {
        dial: "1758",
        name: "Saint Lucia",
        emoji: "🇱🇨",
        iso2: "LC",
        unicode: "\u{1F1F1}\u{1F1E8}",
    },
    {
        dial: "590",
        name: "Saint Martin",
        emoji: "🇲🇫",
        iso2: "MF",
        unicode: "\u{1F1F2}\u{1F1EB}",
    },
    {
        dial: "508",
        name: "Saint Pierre and Miquelon",
        emoji: "🇵🇲",
        iso2: "PM",
        unicode: "\u{1F1F5}\u{1F1F2}",
    },
    {
        dial: "1784",
        name: "Saint Vincent and the Grenadines",
        emoji: "🇻🇨",
        iso2: "VC",
        unicode: "\u{1F1FB}\u{1F1E8}",
    },
    {
        dial: "685",
        name: "Samoa",
        emoji: "🇼🇸",
        iso2: "WS",
        unicode: "\u{1F1FC}\u{1F1F8}",
    },
    {
        dial: "378",
        name: "San Marino",
        emoji: "🇸🇲",
        iso2: "SM",
        unicode: "\u{1F1F8}\u{1F1F2}",
    },
    {
        dial: "239",
        name: "São Tomé and Príncipe",
        emoji: "🇸🇹",
        iso2: "ST",
        unicode: "\u{1F1F8}\u{1F1F9}",
    },
    {
        dial: "966",
        name: "Saudi Arabia",
        emoji: "🇸🇦",
        iso2: "SA",
        unicode: "\u{1F1F8}\u{1F1E6}",
    },
    {
        dial: "221",
        name: "Senegal",
        emoji: "🇸🇳",
        iso2: "SN",
        unicode: "\u{1F1F8}\u{1F1F3}",
    },
    {
        dial: "381",
        name: "Serbia",
        emoji: "🇷🇸",
        iso2: "RS",
        unicode: "\u{1F1F7}\u{1F1F8}",
    },
    {
        dial: "248",
        name: "Seychelles",
        emoji: "🇸🇨",
        iso2: "SC",
        unicode: "\u{1F1F8}\u{1F1E8}",
    },
    {
        dial: "232",
        name: "Sierra Leone",
        emoji: "🇸🇱",
        iso2: "SL",
        unicode: "\u{1F1F8}\u{1F1F1}",
    },
    {
        dial: "65",
        name: "Singapore",
        emoji: "🇸🇬",
        iso2: "SG",
        unicode: "\u{1F1F8}\u{1F1EC}",
    },
    {
        dial: "1721",
        name: "Sint Maarten",
        emoji: "🇸🇽",
        iso2: "SX",
        unicode: "\u{1F1F8}\u{1F1FD}",
    },
    {
        dial: "421",
        name: "Slovakia",
        emoji: "🇸🇰",
        iso2: "SK",
        unicode: "\u{1F1F8}\u{1F1F0}",
    },
    {
        dial: "386",
        name: "Slovenia",
        emoji: "🇸🇮",
        iso2: "SI",
        unicode: "\u{1F1F8}\u{1F1EE}",
    },
    {
        dial: "677",
        name: "Solomon Islands",
        emoji: "🇸🇧",
        iso2: "SB",
        unicode: "\u{1F1F8}\u{1F1E7}",
    },
    {
        dial: "252",
        name: "Somalia",
        emoji: "🇸🇴",
        iso2: "SO",
        unicode: "\u{1F1F8}\u{1F1F4}",
    },
    {
        dial: "27",
        name: "South Africa",
        emoji: "🇿🇦",
        iso2: "ZA",
        unicode: "\u{1F1FF}\u{1F1E6}",
    },
    {
        dial: "82",
        name: "South Korea",
        emoji: "🇰🇷",
        iso2: "KR",
        unicode: "\u{1F1F0}\u{1F1F7}",
    },
    {
        dial: "211",
        name: "South Sudan",
        emoji: "🇸🇸",
        iso2: "SS",
        unicode: "\u{1F1F8}\u{1F1F8}",
    },
    {
        dial: "34",
        name: "Spain",
        emoji: "🇪🇸",
        iso2: "ES",
        unicode: "\u{1F1EA}\u{1F1F8}",
    },
    {
        dial: "94",
        name: "Sri Lanka",
        emoji: "🇱🇰",
        iso2: "LK",
        unicode: "\u{1F1F1}\u{1F1F0}",
    },
    {
        dial: "249",
        name: "Sudan",
        emoji: "🇸🇩",
        iso2: "SD",
        unicode: "\u{1F1F8}\u{1F1E9}",
    },
    {
        dial: "597",
        name: "Suriname",
        emoji: "🇸🇷",
        iso2: "SR",
        unicode: "\u{1F1F8}\u{1F1F7}",
    },
    {
        dial: "47",
        name: "Svalbard and Jan Mayen",
        emoji: "🇸🇯",
        iso2: "SJ",
        unicode: "\u{1F1F8}\u{1F1EF}",
    },
    {
        dial: "268",
        name: "Swaziland",
        emoji: "🇸🇿",
        iso2: "SZ",
        unicode: "\u{1F1F8}\u{1F1FF}",
    },
    {
        dial: "46",
        name: "Sweden",
        emoji: "🇸🇪",
        iso2: "SE",
        unicode: "\u{1F1F8}\u{1F1EA}",
    },
    {
        dial: "41",
        name: "Switzerland",
        emoji: "🇨🇭",
        iso2: "CH",
        unicode: "\u{1F1E8}\u{1F1ED}",
    },
    {
        dial: "963",
        name: "Syria",
        emoji: "🇸🇾",
        iso2: "SY",
        unicode: "\u{1F1F8}\u{1F1FE}",
    },
    {
        dial: "886",
        name: "Taiwan",
        emoji: "🇹🇼",
        iso2: "TW",
        unicode: "\u{1F1F9}\u{1F1FC}",
    },
    {
        dial: "992",
        name: "Tajikistan",
        emoji: "🇹🇯",
        iso2: "TJ",
        unicode: "\u{1F1F9}\u{1F1EF}",
    },
    {
        dial: "255",
        name: "Tanzania",
        emoji: "🇹🇿",
        iso2: "TZ",
        unicode: "\u{1F1F9}\u{1F1FF}",
    },
    {
        dial: "66",
        name: "Thailand",
        emoji: "🇹🇭",
        iso2: "TH",
        unicode: "\u{1F1F9}\u{1F1ED}",
    },
    {
        dial: "670",
        name: "Timor-Leste",
        emoji: "🇹🇱",
        iso2: "TL",
        unicode: "\u{1F1F9}\u{1F1F1}",
    },
    {
        dial: "228",
        name: "Togo",
        emoji: "🇹🇬",
        iso2: "TG",
        unicode: "\u{1F1F9}\u{1F1EC}",
    },
    {
        dial: "690",
        name: "Tokelau",
        emoji: "🇹🇰",
        iso2: "TK",
        unicode: "\u{1F1F9}\u{1F1F0}",
    },
    {
        dial: "676",
        name: "Tonga",
        emoji: "🇹🇴",
        iso2: "TO",
        unicode: "\u{1F1F9}\u{1F1F4}",
    },
    {
        dial: "1868",
        name: "Trinidad and Tobago",
        emoji: "🇹🇹",
        iso2: "TT",
        unicode: "\u{1F1F9}\u{1F1F9}",
    },
    {
        dial: "216",
        name: "Tunisia",
        emoji: "🇹🇳",
        iso2: "TN",
        unicode: "\u{1F1F9}\u{1F1F3}",
    },
    {
        dial: "993",
        name: "Turkmenistan",
        emoji: "🇹🇲",
        iso2: "TM",
        unicode: "\u{1F1F9}\u{1F1F2}",
    },
    {
        dial: "1649",
        name: "Turks and Caicos Islands",
        emoji: "🇹🇨",
        iso2: "TC",
        unicode: "\u{1F1F9}\u{1F1E8}",
    },
    {
        dial: "688",
        name: "Tuvalu",
        emoji: "🇹🇻",
        iso2: "TV",
        unicode: "\u{1F1F9}\u{1F1FB}",
    },
    {
        dial: "1340",
        name: "U.S. Virgin Islands",
        emoji: "🇻🇮",
        iso2: "VI",
        unicode: "\u{1F1FB}\u{1F1EE}",
    },
    {
        dial: "256",
        name: "Uganda",
        emoji: "🇺🇬",
        iso2: "UG",
        unicode: "\u{1F1FA}\u{1F1EC}",
    },
    {
        dial: "971",
        name: "United Arab Emirates",
        emoji: "🇦🇪",
        iso2: "AE",
        unicode: "\u{1F1E6}\u{1F1EA}",
    },
    {
        dial: "598",
        name: "Uruguay",
        emoji: "🇺🇾",
        iso2: "UY",
        unicode: "\u{1F1FA}\u{1F1FE}",
    },
    {
        dial: "998",
        name: "Uzbekistan",
        emoji: "🇺🇿",
        iso2: "UZ",
        unicode: "\u{1F1FA}\u{1F1FF}",
    },
    {
        dial: "678",
        name: "Vanuatu",
        emoji: "🇻🇺",
        iso2: "VU",
        unicode: "\u{1F1FB}\u{1F1FA}",
    },
    {
        dial: "39",
        name: "Vatican City",
        emoji: "🇻🇦",
        iso2: "VA",
        unicode: "\u{1F1FB}\u{1F1E6}",
    },
    {
        dial: "58",
        name: "Venezuela",
        emoji: "🇻🇪",
        iso2: "VE",
        unicode: "\u{1F1FB}\u{1F1EA}",
    },
    {
        dial: "84",
        name: "Vietnam",
        emoji: "🇻🇳",
        iso2: "VN",
        unicode: "\u{1F1FB}\u{1F1F3}",
    },
    {
        dial: "681",
        name: "Wallis and Futuna",
        emoji: "🇼🇫",
        iso2: "WF",
        unicode: "\u{1F1FC}\u{1F1EB}",
    },
    {
        dial: "212",
        name: "Western Sahara",
        emoji: "🇪🇭",
        iso2: "EH",
        unicode: "\u{1F1EA}\u{1F1ED}",
    },
    {
        dial: "967",
        name: "Yemen",
        emoji: "🇾🇪",
        iso2: "YE",
        unicode: "\u{1F1FE}\u{1F1EA}",
    },
    {
        dial: "260",
        name: "Zambia",
        emoji: "🇿🇲",
        iso2: "ZM",
        unicode: "\u{1F1FF}\u{1F1F2}",
    },
    {
        dial: "263",
        name: "Zimbabwe",
        emoji: "🇿🇼",
        iso2: "ZW",
        unicode: "\u{1F1FF}\u{1F1FC}",
    },
    {
        dial: "358",
        name: "Åland Islands",
        emoji: "🇦🇽",
        iso2: "AX",
        unicode: "\u{1F1E6}\u{1F1FD}",
    },
    {
        dial: "7",
        name: "Russia",
        emoji: "🇷🇺",
        iso2: "RU",
        unicode: "\u{1F1F7}\u{1F1FA}",
    },
];
